[workspace]
authors = ["Mihai Maruseac <mihaimaruseac@google.com>"]
channels = ["conda-forge", "bioconda"]
name = "my-project"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
hello = 'echo "Hello, Pixi!"'
greet = { cmd = 'echo "Hello, {{name}}!"', args = ["name"] }

[dependencies]
python = ">=3.13.5,<3.14"
scipy = "==1.15.1"
numpy = ">=2.3.1,<3"
fastqc = { version = ">=0.12.1,<0.13", channel = "bioconda" }
pandas = ">=2.3.0,<3"

[feature.test.pypi-dependencies]
pytest = { git = "https://github.com/pytest-dev/pytest", rev = "8.3.1" }

[environments]
test = { features = ["test"], solve-group = "mm" }
format = { features = ["format"], no-default-feature = true }
default = { solve-group = "mm" }

[feature.format.dependencies]
ruff = "*"
