[workspace]
authors = ["Mihai Maruseac <mihaimaruseac@google.com>"]
channels = ["conda-forge", "bioconda"]
name = "my-project"
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
scipy = ">=1.16.0,<2"
numpy = ">=2.3.1,<3"
